### ISSUE TITLE
Add ability to disable announcement for certain entities

### ISSUE THREAD

**Issue by Naomi-alt** [EvModder/DropHeads#18]
On the server I play on, we use DropHeads. However, there are lots of people with wither skeleton farms, which means that the chat is constantly spammed with dropped heads announcements.

We don't want to tweak the drop rate of the wither skeleton heads, as we don't want to alter the vanilla gameplay to much, so we thought the best idea was to be able to disable the announcement for certain entities/mobs, because we still want to see the other announcements.

I'm guessing the best way to implement this would be to add a `no-announce:` option where you can list all the entities you don't want announced.

And then probably in the `EntityDeathListener` a check to see whether the entity is in the `no-announce` list.

But it's your plugin, so you probably know best how to implement it.

**Comment by EvModder** [comment]
That could work well..
The announce setting (which currently applies to _all_ mobs) has these options: 
`GLOBAL` = to everyone, `LOCAL` = to nearby,`DIRECT` = to killer, and `OFF`

It might be nice to let people set this per-mob, and if a mob isn't specified then it uses the default setting.

I've also been thinking about making it possible to make other config options only apply to a specific set of mobs (basically, make it possibly to completely customize config settings per-mob... for example, on a custom server, what if they wanted to set it up so each mob requires a different, specific tool to kill it with in order to get a head drop, etc.)

I'll think about it a bit more, and make sure do do something for the v3.4.1 release (I'll track updates here)

**Comment by EvModder** [comment]
I think something like this would work:
```
# How to announce beheadings, options are GLOBAL, LOCAL, DIRECT, or OFF
# To customize per-mob, add a line like 'wither_skeleton: DIRECT'
behead-announcement:
  default: 'LOCAL'
  player: 'GLOBAL'
```

(Current config:)
```
# How to announce beheadings, options are GLOBAL, LOCAL, DIRECT, or OFF
behead-announcement-mobs: 'LOCAL'
behead-announcement-players: 'GLOBAL'
```

I will go ahead and make this change, but keep backward support for configs using the old options.
