### ISSUE TITLE
Missing looting drop rate modifier in config?

### ISSUE THREAD

**Issue by Jacold** [EvModder/DropHeads#4]
Hi. While configuring DropHeads plugin I don't found "Adjust looting enchantment drop rate modifier" which is listed on plugin's bukkit page. It was really missed or I missed it?

Cheers,
Jacold.

**Comment by EvModder** [comment]
Oh, I removed this feature a long time ago in favor of using the vanilla looting mechanics for rare drops (+1% per level), and forgot to update the Bukkit page.
If you really want to modify looting drop rates, maybe I can revisit it?
IMO it would be odd to change how looting works unless it gets changes across the board though (including drops besides heads).

**Comment by Jacold** [comment]
[21:02:33 INFO]: [DropHeads] Jacold decapitated Skeleton using [Diamond Sword]
[21:02:33 INFO]: [DropHeads] Dropped Head: SKELETON
Raw chance: 1.0%, SpawnReason Bonus: 0.0%, TimeAlive Bonus: 0.0%, Looting Bonus: 3.0%, Weapon Bonus: 0.0%, Final drop chance: 1.03%

Since that change I can say bye to 5,5% chance to drop wither skeleton skull :p

**Comment by EvModder** [comment]
Looks like the issue is with your wither skeleton drop rate in the config?
raw chance: 1.0% (that should be 2.5% by default, check head-drop-rates.txt)

**Comment by Jacold** [comment]
I mean I wanted to add ability to drop skeleton, zombie and creeper heads with 1% chance affected by looting (+1% each level) but keep base 2,5% (+1% per looting level) for wither skeletons.
Yeah, I wrote previous message in a hurry and I wasn't explained all. Sorry.

**Comment by EvModder** [comment]
No worries! I added the following two config options in v3.3.4 (released yesterday):
looting-multiplier: 1.0
looting-addition: 0.00

If you change the second setting to 0.01 for 1%, that should give the behavior you are looting for.
NOTE: You will need to regenerate the default configuration file for the or add those lines manually to your config, since Bukkit/Spigot doesn't give me an easy way to add new settings to existing/modified config files.
