### ISSUE TITLE
Heads of players who have never joined the server are Steve/Alex in 1.17+

### ISSUE THREAD

**Issue by wubbits19** [EvModder/DropHeads#44]
Through killing or /gethead player: ... doesnt give the actual players head, only Steve.

**Comment by EvModder** [comment]
This seems to be caused by a Spigot API bug (tracked here: https://hub.spigotmc.org/jira/browse/SPIGOT-6558).
But I figured out a way to get it to work for now, I just uploaded the new plugin jar `v3.6.8`, it might take a few hours to process the file but it works for now, as long as the player has joined the server before.

In the case you you need the head of someone who hasn't played before, I suggest this command for now:
`/minecraft:give @p minecraft:player_head{display:{Name:"{\"text\":\"GitHub\"}"},SkullOwner:"MHF_GitHub"} 1`
(just replace the appropriate parts with the name of the player you want)

**Comment by EvModder** [comment]
Spigot seems to have fixed this bug, at least for the most part.
It should only still exist in 1.17 spigot servers, and DropHeads now has a custom way of setting the owner which should make it less affected by this bug.
