### ISSUE TITLE
Shulker Heads

### ISSUE THREAD

**Issue by Wersebu** [EvModder/DropHeads#70]
I cant get upsidedown open shulker heads always droping normal head 
Shulker open normal head - drops
Shulker closed normal head - drops
Shulker side closed - drop
Shulker side opend - DONT DROP
Shulker upsiuede down closed - drops
Shulker upsidedown opend -DONT DROP

Plis fast help

**Comment by EvModder** [comment]
Hmm, issue could be from a few possibilities:
* Make sure to kill the right Shulkers -- upside down drops if Shulker is attached to the bottom of a block (same for side)
* The heads will need to be in head-textures.txt in order to get dropped (check if the file needs updating)
* Sideways and upside-down Shulkers only work in Minecraft 1.17+ (and DropHeads 3.7+)
* Open heads only drop when the Shulker is open (shooting at someone), and not 100% of the time because client and server side can sometimes disagree on whether it is open
* might be a bug in the code since this feature is new, so I'll do some tests

**Comment by EvModder** [comment]
Let me know if you're still having problems with this (so far I cannot replicate it myself)
