### ISSUE TITLE
Player Head Textures Update even when Setting set to False

### ISSUE THREAD

**Issue by kelancombe** [EvModder/DropHeads#73]
We noticed on our server the other day while applying new skins that the player head textures update when the player changes their skin. This only happens when the head is dropped or broken. This happens even though the setting "update-on-skin-change" is set to false.

**Comment by EvModder** [comment]
Ah, seems like this bug was introduced in a recent version. I should have an update out to fix it this weekend

**Comment by EvModder** [comment]
Actually, I found a bit of a complication -- if I remove the player's UUID from the head's profile, it will keep the texture even when the player changes their skin, however since it no longer has the player's UUID the plugin cannot link it to a player, so it gets treated like a custom/decoration head, and doesn't know what player it came from.

Kind of a tricky thing to balance, but I think I might have an idea for how to keep it associated with the correct player while still retaining texture, however it might be a bit more complicated and require some testing so I might push it back until v3.7.8

**Comment by EvModder** [comment]
Alright, in my dev build I've got it to work for heads of players who are online (which will always be the case for dropped heads), however if you use `/gethead` to spawn the head of an **offline** player it currently will *not* freeze the texture (i.e., it will still update if placed and mined).

IMO this should be a good enough fix for now, and I honestly think that keeping heads with the original texture from when the beheading happened makes a lot of sense so I set it as the default in the config (won't affect any existing config or people using the plugin, just fresh new config installs)

**Comment by EvModder** [comment]
(Fixed in v3.7.7)

**Comment by kelancombe** [comment]
That is ok! I appreciate you looking into it and being so speedy with your
response. I understand these things take time and until then we are going
to keep using your fantastic plugin and find our own work-arounds.
