### ISSUE TITLE
Unable to parse death message 

### ISSUE THREAD

**Issue by pepsiliberty** [EvModder/DropHeads#81]
Attached is a screenshot in console, seems to happen occasionally when a player dies. 
![Screenshot_2022-10-09-14-11-09-20_572064f74bd5f9fa804b05334aa4f912](https://user-images.githubusercontent.com/115386750/194737992-ac006d41-1b4b-4bee-a1f0-09f027356d7a.jpg)

Thanks in advance!!

**Comment by EvModder** [comment]
Hmm, thanks for sharing the error I think I see the part it is failing to parse but I don't know why it generated that way.

Is there any chance you are using any other plugins which customize death messages?
Also, would you mind sharing your settings for `message-beheaded` in [translations.yml](https://github.com/EvModder/DropHeads/blob/master/translations.yml)

**Comment by pepsiliberty** [comment]
I thought it could be our Graves plugin maybe?
The error doesn't show up every time a player dies, but I haven't been able to recreate it intentionally and narrow down what situation causes it. 
The grave plugin that we use is https://www.spigotmc.org/resources/graves.74208/
![Uploading Screenshot_2022-10-10-19-50-42-07_40deb401b9ffe8e1df2f1cc5ba480b12.jpg…]()

**Comment by EvModder** [comment]
(Copying this here for self-reference so I can pull it up later on my laptop to do some testing):
`{"translate":"death.attack.mob","with":[{"text":"NameN0tRequired"},{"extra":[{"color":"#528cff","text":"Lvl 21"},{"color":"dark_gray","text":""},{"translate":"entity.minecraft.piglin_brute"}],"text":""}]}`

**Comment by EvModder** [comment]
Ah, so I found the problem. DH is trying to figure out the player's UUID in the vanilla death message so it can cancel the packet and replace it with the DH behead message.

In vanilla, the game uses `{"selector":"uuid_here"}` to specify the player in a death message (selectors display the player's name, if you hover over it in chat it will also show the entity type and uuid).
However, Graves (presumably; or perhaps another plugin) is replacing it with `{"text":"NameN0tRequired"}, which means that DH still identifies it as a behead message but fails to extract the UUID

**Comment by EvModder** [comment]
@pepsiliberty 
I had a peek at the Graves source code, and I didn't see anywhere modifying the death message (or generating a custom one), so I wanted to check with you if there are any other plugins installed you think might be reading/editing death messages?

Mainly so I can try to submit a PR to whichever plugin is doing it to update their code to use UUIDs, if the author approves

**Comment by pepsiliberty** [comment]
Thank you for checking it out! 

I thought perhaps Graves since it creates a Holo display above the grave with the player's name + reason for death. Other than that, I can't see another plugin that has anything to do with death messages, I'm sorry!

**Comment by EvModder** [comment]
I contacted the author of Graves and they confirmed it doesn't modify death messages, so I'm thinking it might be something else.

Digging into the error message, my guess is it's probably caused by the same thing that is adding the "Lvl 21 | <mob name>" text into the death message

Here's a screenshot of what it looks like, based on the tellraw message in the error
<img width="267" alt="Screen Shot 2022-10-18 at 4 09 13 PM" src="https://user-images.githubusercontent.com/5511002/196545434-131535a6-ca0b-4677-9872-489360d8a0c2.png">

**Comment by pepsiliberty** [comment]
Ah! So sorry for slow reply. That would be Levelled Mobs plugin

**Comment by EvModder** [comment]
No worries, sometimes I'm slow with responses as well.
I can confirm that the issue is being caused by [Levelled Mobs](https://github.com/lokka30/LevelledMobs/blob/master/src/main/java/me/lokka30/levelledmobs/listeners/PlayerDeathListener.java), possibly in combination with [Mythic Mobs](https://www.spigotmc.org/resources/%E2%9A%94-mythicmobs-free-version-%E2%96%BAthe-1-custom-mob-creator%E2%97%84.5702/)

I sent a PR request to the owner of Levelled Mobs which fixes the issue, if/once they approve it and update that plugin it should no longer cause this compatibility error :)

**Comment by EvModder** [comment]
Good news!
It looks like the author of Levelled Mobs approved the fix I sent to their death message system [here](https://github.com/lokka30/LevelledMobs/pull/419), so probably in this release or the next of it the compatibility errors should be gone
