### ISSUE TITLE
{suggestion} toggle headdrop messages

### ISSUE THREAD

**Issue by sovtec** [EvModder/DropHeads#83]
Add a toggle for both local headdrop messages (when mobs are beheaded) and for global headdrop messages (when players are beheaded) so that players can use command ex: **/toggledrop mobs** **/toggledrop players** to ignore/toggle dropmessages for players and mobs. 

Will be usefull for ignoring messages if someone is spawnkilling someone (/toggledrop players) and can be used to ignore your own local mob headdrop messages (/toggledrop mobs) if you are farming mobs and get spammed by the drophead message

**Comment by EvModder** [comment]
I have a partial fix for this in v3.7.8, which is a config option to control whether the `dropheads.silentbehead` permission hides behead your messages from everyone, yourself, or just other players, however there currently isn't a command to toggle this permission on yourself.

If you have a permission plugin that can dynamically add/remove perms, you could maybe set up a Spigot alias for `/togglebeheadmsg` -> `/perm toggle <player> dropheads.silentbehead` (using a `PermissionsBukkit` command in that example, other permission plugins probably have something similar)

**Comment by EvModder** [comment]
Marking as closed since the [Extras page](https://dev.bukkit.org/projects/dropheads/pages/extras) now includes the [MuteDeaths](https://github.com/EvModder/MuteDeaths) plugin (which can also mute/ignore beheads based on killer or victim)

Hopefully any folks searching for this in the future will be able to find it through the links here.
