### ISSUE TITLE
Paintings and item frames dropping textureless "heads."

### ISSUE THREAD

**Issue by kriskane** [EvModder/DropHeads#87]
Breaking paintings and item frames results in the item and a mob head dropping. The mob heads are labeled "mob:painting" or mob:item_frame."

Running git-Paper-279 (MC: 1.19.2).

log entries:
1669380877517,mob decapitated,Item Frame,Crash_Panda_,[block.minecraft.iron_bars]
1669380886860,mob decapitated,Item Frame,Crash_Panda_,[item.minecraft.item_frame]
1669380887209,mob decapitated,Item Frame,Crash_Panda_,[item.minecraft.item_frame]
1669380951141,mob decapitated,Painting,PirateBingo,[item.minecraft.painting]
1669380953289,mob decapitated,Item Frame,PirateBingo,[item.minecraft.item_frame]
1669380995466,mob decapitated,Item Frame,Crash_Panda_,[item.minecraft.item_frame]
1669381035722,mob decapitated,Item Frame,PirateBingo,[item.minecraft.item_frame]

Would be happy to help debug, contact bingo#0420 or unkul#0060 on discord, and thanks!

**Comment by EvModder** [comment]
Sorry for the late response!
I've been MIA on github and bukkit for a while due to travel, but the easiest solution here would be to set the drop chance for paintings and item_frames to 0 in [plugins/DropHeads/head-drop-rates.txt ](https://github.com/EvModder/DropHeads/blob/master/head-drop-rates.txt#L83)

As you can see in the default config, I apparently forgot to add those to the file along with the other nonliving entities which are explicitly set to 0$ (I'll add them in the next version release), so anyone using a default droprate of > 0 will probably be having the same issue until they set painting & item_frame to 0 as well.

Once again sorry for the slow response!

**Comment by EvModder** [comment]
Fixed for the default config in https://github.com/EvModder/DropHeads/commit/38a12ea55edf06e4498d26ff59d2b7df36f20b1c
