### ISSUE TITLE
Placeholder API

### ISSUE THREAD

**Issue by ValhallaCraft** [EvModder/DropHeads#88]
Can we get some placeholders for like %dropheads_total_beheaded% and %dropheads_total_beheaded_MOB:mobname%?

**Comment by EvModder** [comment]
Hmm, I haven't worked with Placeholder API before but it looks like getting those should be pretty straightforward.
An alternative workaround (if you do a bit of coding) is to extract that data from the `plugins/DropHeads/dropheads-log.txt`, which is basically just a spreadsheet (comma separated values, each row/line is a behead event).

**Comment by ValhallaCraft** [comment]
The placeholders i feel would be a huge addition because it would allow players to make leaderboards and other things for how many heads players have collected!

**Comment by EvModder** [comment]
Yes indeed.  I'll probably start with vanilla scoreboards, since they are a bit more universal than Placeholder API, but I can probably do them both together (creating parallel addons for each) since there is probably a ton of code similarity.

There are also a few design decisions that need to be made; if either of you (or anyone reading this) has opinions on these or can think of any other problems, please feel free to comment below:

**1. Aggregates**
I assume we want a per-player counter for sum total beheads, total mob beheads, and total player beheads.  But should there also be a counter per-mob?  What about per-sub-mob?  (E.g., `mob:sheep:red` or `villager:desert:librarian`)
Also, in vanilla there are certain "groups" of mobs, i.e., the ones you see in tab-complete any time you run any command with an entity selector (e.g. `#skeletons`, `#raiders`, `#powder_snow_walkable_mobs`), do we want to have placeholders for these combined headcounts as well?
What about even broader groups not defined in vanilla, such as "monsters beheaded", "nether mobs beheaded", "arthropods beheaded"?

**2. Beheader vs beheaded **
Do we also want to track statistics/placeholders for how many times a player has lost their head?  Or how many times a certain type of entity has been beheaded?  Aggregates also apply here.

**3. Type of behead **
How should charged creeper explosions be counted in statistics?  (Especially considering it is a feature enabled in the default config, and many servers use it as the *only* way to get heads for all or certain mobs).  Does the statistic / placeholder get incremented for the entity the charged creeper was targeting, AKA the player, or does it have its own statistic?  Also, should there be separate statistics depending on if the beheading happened with a sword vs. axe vs. bow & arrow?  (Once again, it's not an issue for some servers that prevent beheading by limiting it to a single tool type like gold axe, but it becomes a problem on servers that allow any type of behead, even if a mob dies on it's own without the player, such as fall damage).

If anyone out there is a developer and wants to take on the challenges described above and develop the addon for this (stats / placeholders), I would be happy to assist and point to relevant part of DropHeads API (such as [the existing head-drop logging](https://github.com/EvModder/DropHeads/search?q=writeToLogFile)).  Otherwise, well I will eventually get it done but I tend to be a bit of a perfectionist for these sort of things (and because I worry about backwards-compatibility) so it might be a while.

An unrelated but similar request that I've received and also intend to do (as an addon) is a behead-counter on swords for players to show off with item-sharing in chat, which is much more limited in scope and thus easier to do, so I might start with that.

**Comment by sovtec** [comment]
I would suggest perhaps having the option to add the placeholders for custom mobs but having placeholders for default mob types as standard.

I know there are a lot of variations but I think it's best to have placeholders EX: beheaded bees = all total beheaded bees from all types. To create a *%beheaded_bees_total%* placeholder for that, and if a user wants he can input the placeholder for the spesific mob type manually, allrho it's probably best to have placeholder for both all types and combination of types within a mob. 
EX:
%beheaded_bees_total%
%beheaded_bees_grum%

%beheaded_axolotl_total%
%beheaded_axolotl_blue_grum%

As for the creeper headdrop, it should be a option in config to enable/disable explosions headdrop "logging" caused by mobs.

That's a lot of placeholders to add so mabye do a small update with the main mob types first and see how hard it is to implement, then you can implement that while having the option in your head for "detailed" mob placeholders in the future

**Comment by ValhallaCraft** [comment]
You should look into how the statistic placeholder does blocks mined. They have %statistic_block_mine% for total blocks mined. And then they do %statistic_block_mine:<block type>%. Probably the best way to do the different types of mobs vs total mobs. Also, I wouldn't worry to much about the subcategories of each mob. Maybe down the line, but for now I wouldn't see that as necessary because there are thousands of them

**Comment by sovtec** [comment]
> You should look into how the statistic placeholder does blocks mined. They have %statistic_block_mine% for total blocks mined. And then they do %statistic_block_mine:<block type>%. Probably the best way to do the different types of mobs vs total mobs. 

I am going to test if AJ Leaderboards can be used without further configuration, will post how it went

**Comment by ValhallaCraft** [comment]
> > You should look into how the statistic placeholder does blocks mined. They have %statistic_block_mine% for total blocks mined. And then they do %statistic_block_mine:%. Probably the best way to do the different types of mobs vs total mobs.
> 
> I am going to test if AJ Leaderboards can be used without further configuration, will post how it went

That's what I use for these exact stats!

**Comment by ajgeiss0702** [comment]
> > You should look into how the statistic placeholder does blocks mined. They have %statistic_block_mine% for total blocks mined. And then they do %statistic_block_mine:%. Probably the best way to do the different types of mobs vs total mobs.
> 
> I am going to test if AJ Leaderboards can be used without further configuration, will post how it went

All ajLeaderboards needs is a placeholder that returns a number.

I haven’t used this plugin before, but from my understanding all you would need is to add a placeholder for number of beheadings the player has. That is enough for ajLeaderboards to create a beheadings leaderboard

A currently working example would be the %statistic_player_kills% placeholder. That placeholder just returns the number of players that the player viewing the placeholder has killed. That’s all ajLeaderboards needs to make a leaderboard.

**Comment by EvModder** [comment]
I took a look at Placeholder API (specifically, adding custom expansions) and it appears there is no built-in data storage, which is fine but it means I need a place to store the aggregated stats server side. I was considering doing it in `/plugins/DropHeads/behead_stats.csv` but the file size would grow way too quickly on big servers, so I think I'll just have an option to write it to a vanilla scoreboard, and then I'll make a Placeholder API expansion that lets you read existing scoreboard/statistics values, in case no one else has done that already.

**Comment by EvModder** [comment]
Goodness, I didn't realize I never responded here - this should be fully possible now with a plugin hooking into DropHeads' API like [EvStats](https://github.com/EvModder/EvStats) (let me know if you want me to generate the .jar for you), in combination with [AJ leaderboards](https://www.spigotmc.org/resources/ajleaderboards.85548/) and/or [ObjectiveExpansion](https://www.spigotmc.org/resources/placeholderapi-scoreboard-objectives-placeholder.48236/).

I haven't made a public release on Bukkit/Spigot/Modrinth for EvStats yet, but basically it takes available vanilla statistics and some easily-accessible plugin API stats and generates Scoreboards for them. ObjectiveScoreboards is a Placeholder Expansion which provides a placeholder for Scoreboard values. PAPI-based plugins like ajScoreboards can then use the expansion to read scoreboards, and display it however they want.

Sorry, quite the mouthful of jargon,.. but yea :)
