### ISSUE TITLE
Feature request: animated heads

### ISSUE THREAD

**Issue by NBS-Paste** [EvModder/DropHeads#99]
It would be cool if mobs that had floppy ears such as the piglin had their ears animated so that they flopped as you walk. I know its not necessary but a player on my server thought it would be cool.

**Comment by NBS-Paste** [comment]
I would be open to adding a datapack or resource pack to the server for this, but if you don't want to work on it I totally get it.

**Comment by EvModder** [comment]
Yeah tbh it's partly because I have very little experience making client mods or datapacks, so for this feature I have no clue where even to start..

I'm sure someone out there will have the necessary knowledge, and it sounds like the kind of feature that can be done completely independently of DropHeads, so if it's something you'd really want to see I encourage you to see if you can find such a person.

And if you do, feel free send/link it to me, I can post a link to it from the `DropHeads > Extras` page for others who might appreciate it as well :)
